name: haskell-import-graph
version: 1.0.4
synopsis: create haskell import graph for graphviz
category: Development
author: ncaq
maintainer: ncaq@ncaq.net
copyright: © ncaq
license: MIT
github: ncaq/haskell-import-graph

ghc-options:
  - -Wall
  # - -Wall-missed-specialisations
  - -Widentities
  # - -Wimplicit-prelude
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  # - -Wmissed-specialisations
  # - -Wmissing-export-lists
  - -Wmissing-exported-signatures
  - -Wmissing-home-modules
  # - -Wmissing-import-lists
  # - -Wmissing-local-signatures
  # - -Wmonomorphism-restriction
  # - -Wpartial-fields
  - -Wredundant-constraints
  - -Wcompat
  - -O2

library:
  source-dirs: lib
  dependencies:
    - base >= 4.8 && < 5
    - classy-prelude
    - ghc
    - graphviz
    - process
    - text
    - transformers

executables:
  haskell-import-graph:
    main: Main.hs
    source-dirs: exec
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - haskell-import-graph
